// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package oidc

import (
	"reflect"

	di "github.com/fluffy-bunny/sarulabsdi"
)

// ReflectTypeIOidcBackgroundStorage used when your service claims to implement IOidcBackgroundStorage
var ReflectTypeIOidcBackgroundStorage = di.GetInterfaceReflectType((*IOidcBackgroundStorage)(nil))

// AddSingletonIOidcBackgroundStorageByObj adds a prebuilt obj
func AddSingletonIOidcBackgroundStorageByObj(builder *di.Builder, obj interface{}) {
	di.AddSingletonWithImplementedTypesByObj(builder, obj, ReflectTypeIOidcBackgroundStorage)
}

// AddSingletonIOidcBackgroundStorage adds a type that implements IOidcBackgroundStorage
func AddSingletonIOidcBackgroundStorage(builder *di.Builder, implType reflect.Type) {
	di.AddSingletonWithImplementedTypes(builder, implType, ReflectTypeIOidcBackgroundStorage)
}

// AddSingletonIOidcBackgroundStorageByFunc adds a type by a custom func
func AddSingletonIOidcBackgroundStorageByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error)) {
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, ReflectTypeIOidcBackgroundStorage)
}

// AddTransientIOidcBackgroundStorage adds a type that implements IOidcBackgroundStorage
func AddTransientIOidcBackgroundStorage(builder *di.Builder, implType reflect.Type) {
	di.AddTransientWithImplementedTypes(builder, implType, ReflectTypeIOidcBackgroundStorage)
}

// AddTransientIOidcBackgroundStorageByFunc adds a type by a custom func
func AddTransientIOidcBackgroundStorageByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error)) {
	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, ReflectTypeIOidcBackgroundStorage)
}

// AddScopedIOidcBackgroundStorage adds a type that implements IOidcBackgroundStorage
func AddScopedIOidcBackgroundStorage(builder *di.Builder, implType reflect.Type) {
	di.AddScopedWithImplementedTypes(builder, implType, ReflectTypeIOidcBackgroundStorage)
}

// AddScopedIOidcBackgroundStorageByFunc adds a type by a custom func
func AddScopedIOidcBackgroundStorageByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error)) {
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, ReflectTypeIOidcBackgroundStorage)
}

// RemoveAllIOidcBackgroundStorage removes all IOidcBackgroundStorage from the DI
func RemoveAllIOidcBackgroundStorage(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeIOidcBackgroundStorage)
}

// GetIOidcBackgroundStorageFromContainer alternative to SafeGetIOidcBackgroundStorageFromContainer but panics of object is not present
func GetIOidcBackgroundStorageFromContainer(ctn di.Container) IOidcBackgroundStorage {
	return ctn.GetByType(ReflectTypeIOidcBackgroundStorage).(IOidcBackgroundStorage)
}

// SafeGetIOidcBackgroundStorageFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetIOidcBackgroundStorageFromContainer(ctn di.Container) (IOidcBackgroundStorage, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeIOidcBackgroundStorage)
	if err != nil {
		return nil, err
	}
	return obj.(IOidcBackgroundStorage), nil
}
