// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package timeutils

import (
	"reflect"

	di "github.com/fluffy-bunny/sarulabsdi"
)

// ReflectTypeITimeUtils used when your service claims to implement ITimeUtils
var ReflectTypeITimeUtils = di.GetInterfaceReflectType((*ITimeUtils)(nil))

// AddSingletonITimeUtils adds a type that implements ITimeUtils
func AddSingletonITimeUtils(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITimeUtils)
	di.AddSingletonWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddSingletonITimeUtilsByObj adds a prebuilt obj
func AddSingletonITimeUtilsByObj(builder *di.Builder, obj interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITimeUtils)
	di.AddSingletonWithImplementedTypesByObj(builder, obj, implementedTypes...)
}

// AddSingletonITimeUtilsByFunc adds a type by a custom func
func AddSingletonITimeUtilsByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITimeUtils)
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddTransientITimeUtils adds a type that implements ITimeUtils
func AddTransientITimeUtils(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITimeUtils)
	di.AddTransientWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddTransientITimeUtilsByFunc adds a type by a custom func
func AddTransientITimeUtilsByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITimeUtils)
	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddScopedITimeUtils adds a type that implements ITimeUtils
func AddScopedITimeUtils(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITimeUtils)
	di.AddScopedWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddScopedITimeUtilsByFunc adds a type by a custom func
func AddScopedITimeUtilsByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITimeUtils)
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// RemoveAllITimeUtils removes all ITimeUtils from the DI
func RemoveAllITimeUtils(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeITimeUtils)
}

// GetITimeUtilsFromContainer alternative to SafeGetITimeUtilsFromContainer but panics of object is not present
func GetITimeUtilsFromContainer(ctn di.Container) ITimeUtils {
	return ctn.GetByType(ReflectTypeITimeUtils).(ITimeUtils)
}

// GetManyITimeUtilsFromContainer alternative to SafeGetManyITimeUtilsFromContainer but panics of object is not present
func GetManyITimeUtilsFromContainer(ctn di.Container) []ITimeUtils {
	objs := ctn.GetManyByType(ReflectTypeITimeUtils)
	var results []ITimeUtils
	for _, obj := range objs {
		results = append(results, obj.(ITimeUtils))
	}
	return results
}

// SafeGetITimeUtilsFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetITimeUtilsFromContainer(ctn di.Container) (ITimeUtils, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeITimeUtils)
	if err != nil {
		return nil, err
	}
	return obj.(ITimeUtils), nil
}

// SafeGetManyITimeUtilsFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetManyITimeUtilsFromContainer(ctn di.Container) ([]ITimeUtils, error) {
	objs, err := ctn.SafeGetManyByType(ReflectTypeITimeUtils)
	if err != nil {
		return nil, err
	}
	var results []ITimeUtils
	for _, obj := range objs {
		results = append(results, obj.(ITimeUtils))
	}
	return results, nil
}

// ReflectTypeITime used when your service claims to implement ITime
var ReflectTypeITime = di.GetInterfaceReflectType((*ITime)(nil))

// AddSingletonITime adds a type that implements ITime
func AddSingletonITime(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITime)
	di.AddSingletonWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddSingletonITimeByObj adds a prebuilt obj
func AddSingletonITimeByObj(builder *di.Builder, obj interface{}, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITime)
	di.AddSingletonWithImplementedTypesByObj(builder, obj, implementedTypes...)
}

// AddSingletonITimeByFunc adds a type by a custom func
func AddSingletonITimeByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITime)
	di.AddSingletonWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddTransientITime adds a type that implements ITime
func AddTransientITime(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITime)
	di.AddTransientWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddTransientITimeByFunc adds a type by a custom func
func AddTransientITimeByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITime)
	di.AddTransientWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// AddScopedITime adds a type that implements ITime
func AddScopedITime(builder *di.Builder, implType reflect.Type, implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITime)
	di.AddScopedWithImplementedTypes(builder, implType, implementedTypes...)
}

// AddScopedITimeByFunc adds a type by a custom func
func AddScopedITimeByFunc(builder *di.Builder, implType reflect.Type, build func(ctn di.Container) (interface{}, error), implementedTypes ...reflect.Type) {
	implementedTypes = append(implementedTypes, ReflectTypeITime)
	di.AddScopedWithImplementedTypesByFunc(builder, implType, build, implementedTypes...)
}

// RemoveAllITime removes all ITime from the DI
func RemoveAllITime(builder *di.Builder) {
	builder.RemoveAllByType(ReflectTypeITime)
}

// GetITimeFromContainer alternative to SafeGetITimeFromContainer but panics of object is not present
func GetITimeFromContainer(ctn di.Container) ITime {
	return ctn.GetByType(ReflectTypeITime).(ITime)
}

// GetManyITimeFromContainer alternative to SafeGetManyITimeFromContainer but panics of object is not present
func GetManyITimeFromContainer(ctn di.Container) []ITime {
	objs := ctn.GetManyByType(ReflectTypeITime)
	var results []ITime
	for _, obj := range objs {
		results = append(results, obj.(ITime))
	}
	return results
}

// SafeGetITimeFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetITimeFromContainer(ctn di.Container) (ITime, error) {
	obj, err := ctn.SafeGetByType(ReflectTypeITime)
	if err != nil {
		return nil, err
	}
	return obj.(ITime), nil
}

// SafeGetManyITimeFromContainer trys to get the object by type, will not panic, returns nil and error
func SafeGetManyITimeFromContainer(ctn di.Container) ([]ITime, error) {
	objs, err := ctn.SafeGetManyByType(ReflectTypeITime)
	if err != nil {
		return nil, err
	}
	var results []ITime
	for _, obj := range objs {
		results = append(results, obj.(ITime))
	}
	return results, nil
}
