// Code generated by protoc-gen-go-di. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpcdotnetgo "github.com/fluffy-bunny/grpcdotnetgo"
	dicontext "github.com/fluffy-bunny/grpcdotnetgo/middleware/dicontext"
	sarulabsdi "github.com/fluffy-bunny/sarulabsdi"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpcdotnetgo.SupportPackageIsVersion7

func setNewField_BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk(dst interface{}, field string) {
	v := reflect.ValueOf(dst).Elem().FieldByName(field)
	if v.IsValid() {
		v.Set(reflect.New(v.Type().Elem()))
	}
}

// IGreeterService defines the required downstream service interface
type IGreeterService interface {
	SayHello(request *HelloRequest) (*HelloReply, error)
}

// IGreeterService reflect type
var TypeIGreeterService = sarulabsdi.GetInterfaceReflectType((*IGreeterService)(nil))

// GetGreeterServiceFromContainer fetches the downstream di.Request scoped service
func GetGreeterServiceFromContainer(ctn sarulabsdi.Container) IGreeterService {
	return ctn.GetByType(TypeIGreeterService).(IGreeterService)
}

// Impl for Greeter server instances
type greeterServer struct {
	UnimplementedGreeterServer
}

func RegisterGreeterServerDI(s grpc.ServiceRegistrar) {
	// Register the server
	RegisterGreeterServer(s, &greeterServer{})
}

func (s *greeterServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := GetGreeterServiceFromContainer(requestContainer)
	return downstreamService.SayHello(request)
}

// IGreeter2Service defines the required downstream service interface
type IGreeter2Service interface {
	SayHello(request *HelloRequest) (*HelloReply2, error)
}

// IGreeter2Service reflect type
var TypeIGreeter2Service = sarulabsdi.GetInterfaceReflectType((*IGreeter2Service)(nil))

// GetGreeter2ServiceFromContainer fetches the downstream di.Request scoped service
func GetGreeter2ServiceFromContainer(ctn sarulabsdi.Container) IGreeter2Service {
	return ctn.GetByType(TypeIGreeter2Service).(IGreeter2Service)
}

// Impl for Greeter2 server instances
type greeter2Server struct {
	UnimplementedGreeter2Server
}

func RegisterGreeter2ServerDI(s grpc.ServiceRegistrar) {
	// Register the server
	RegisterGreeter2Server(s, &greeter2Server{})
}

func (s *greeter2Server) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply2, error) {
	requestContainer := dicontext.GetRequestContainer(ctx)
	downstreamService := GetGreeter2ServiceFromContainer(requestContainer)
	return downstreamService.SayHello(request)
}

// M_helloworldFullMethodNameEmptyResponseMap keys match that of grpc.UnaryServerInfo.FullMethodName
// i.e. /helloworld.Greeter/SayHello
var M_helloworldFullMethodNameWithErrorResponseMap = map[string]func() interface{}{
	"/helloworld.Greeter/SayHello": func() interface{} {
		ret := &HelloReply{}
		setNewField_BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk(ret, "Error")
		return ret
	},
	"/helloworld.Greeter2/SayHello": func() interface{} {
		ret := &HelloReply2{}
		setNewField_BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk(ret, "Error")
		return ret
	},
}
